### ISSUE TITLE
[GH Request] Add Backstage instance link to openedx-backstage About section

### ISSUE THREAD

**Issue by jmbowman** [openedx/openedx-backstage#23]
### Firm Name

2U

### Urgency

Low urgence - done in next 3 weeks is fine

### Problem/Request

There's no link to https://backstage.openedx.org/ anywhere on https://github.com/openedx/openedx-backstage/ .  Can we please add one, probably in the About section?

### Reasoning

The discoverability of the Open edX Backstage instance is pretty poor.  It comes up if you do a web search directly for "open edx backstage", but if you don't know to look for it it's still pretty hard to find.  And it should definitely be possible to get there directly from the openedx-backstage repository, as configuring that instance is its sole purpose in existing.

**Comment by kdmccormick** [comment]
Sorry @jmbowman , when you asked in Slack earlier I figured you could just open a PR, but I only realized now that you're talking about the About section which isn't version controlled. I'll make the change now.
